# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.

export ZSH=/Users/breakwang/.oh-my-zsh
export EDITOR=vim
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# jumpserver
alias j='ssh wangxianbao@172.18.1.95'
alias xj='ssh wangxianbao@172.18.12.60'
alias aj='ssh root@47.104.0.162'

# cvm
alias cvm='ssh root@192.144.140.39'

#my vm-server
alias v1='ssh root@172.18.2.25'
alias v2='ssh root@172.18.2.26'
alias v3='ssh root@172.18.2.36'
alias va='ssh root@172.18.2.27'
alias cva='ssh root@172.18.2.32'
alias vd1='ssh root@172.18.2.39'
alias vd2='ssh root@172.18.2.40'
alias vd3='ssh root@172.18.2.41'

#liurong && lurongrong
alias lr='ssh root@172.18.2.27'
alias lrr='ssh root@172.18.2.37'
alias cc30='ssh root@172.18.2.30'
alias cc34='ssh root@172.18.2.34'

#office idc phy server (used as vm)
alias p1='ssh root@172.18.2.21'
alias p2='ssh root@172.18.2.22'

#prod
alias ed='ssh root@115.238.170.248'
alias 3copy='ssh root@115.238.170.166'
alias 2copy='ssh root@115.231.180.165'
alias edge='ssh root@115.238.170.173'
alias log='ssh root@115.238.170.172'
alias seattle='ssh root@63.237.232.165'
alias de="ssh root@183.136.205.28"
# command shortcut key
alias sp='cat .ssh/id_rsa.pub | pbcopy'
alias 11='echo celeritas | pbcopy'

alias tn="tmux new -s break"
alias ta="tmux a -t break"
alias py="python"
alias s2-init="cd /Users/breakwang/baishan_code/s2-init"
alias s2="cd /Users/breakwang/baishan_code/s2"

alias zsh="vim .zshrc"
alias szsh="source .zshrc"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git autojump osx node npm)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
